# Generated by Django 4.0.4 on 2022-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('image', models.ImageField(upload_to='item_images', verbose_name='изображение')),
                ('name', models.CharField(max_length=100, verbose_name='текст')),
                ('range', models.CharField(choices=[('daily', 'Посуточно'), ('monthly', 'Помесячно')], default='daily', max_length=20, null=True, verbose_name='аренда')),
                ('flat_count', models.IntegerField(verbose_name='количество комнат')),
                ('floor', models.IntegerField(verbose_name='этажность')),
                ('bed_count', models.IntegerField(verbose_name='спальные места')),
                ('balcony_count', models.IntegerField(verbose_name='балконы')),
                ('bathroom_count', models.IntegerField(verbose_name='ванные места')),
                ('landmark', models.CharField(max_length=50, verbose_name='рядом есть')),
                ('description', models.TextField(default='', verbose_name='описание')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('price', models.IntegerField(default=5000, verbose_name='цена')),
                ('number', models.CharField(default=87762035150, max_length=13, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='в квартире есть')),
                ('building', models.ManyToManyField(related_name='amenitieses', to='flat.building', verbose_name='здание')),
            ],
            options={
                'verbose_name': 'удобства',
                'verbose_name_plural': 'удобствы',
                'ordering': ('text',),
            },
        ),
    ]
